// Generated by scripts/generate-examples.mjs; edit the source in the repository.
// =====================================================================
// pizzeria node — the PROCESS entrypoint of one serving node
// =====================================================================
// The unchanged template process (template/node.ts runNodeProcess) around
// the pizzeria definition: replica line, local token gate, the per-role
// facades and view lines derived from THIS node's mirror, forward-by-token,
// register/heartbeat, the own-row leave. Env: SERVICE_NODE_ID,
// SERVICE_UPSTREAM, SERVICE_NODE_TOKEN, SERVICE_TOKEN_SECRET, SERVICE_PORT.

import {runNodeProcess} from './node'
import {serviceDefinition} from './service'

runNodeProcess({definition: serviceDefinition}).catch(function fatal(error) {
    console.error(error)
    process.exit(2)
})
