// Generated by scripts/generate-examples.mjs; edit the source in the repository.
// =====================================================================
// pizzeria — the domain module: roles, multi-level access, one order flow
// =====================================================================
// The ONLY authored file of the service. Five audiences share one state and
// see five different panels:
//   customer  — the public menu, MY orders, place/cancel
//   cook      — the kitchen board (no contacts), start cooking / mark ready
//   courier   — the dispatch board (address + phone of ready orders), pick up / deliver
//   manager   — kitchen + dispatch + staff (no secrets), edits the menu
//   owner     — everything above + revenue, assigns roles
// Every rule of WHO may do WHAT is data in this file: `allow` on commands
// (pruned from facades AND refused by the authority), `allow` on views
// (served only inside matching principals' facades, derived per session or
// per process). Password hashes live in state so every node can verify a
// login — and no view projects them.

import {createHash} from 'node:crypto'
import {Command} from 'wenay-common2'
import {schemaCommand} from './input-schema'
import type {ServiceCommandCtx, tServiceDefinition, tServicePrincipal} from './leader'
import {hashSecret, verifySecret, type tSecret} from './identity'

// ============================================================
// state
// ============================================================

export const ROLES = ['customer', 'cook', 'courier', 'manager', 'owner'] as const
export type tRole = typeof ROLES[number]

export type Account = {account: string, name: string, phone: string, roles: tRole[], secret: tSecret}
export type MenuItem = {id: string, title: string, price: number, available: boolean}
export type tOrderState = 'placed' | 'cooking' | 'ready' | 'delivering' | 'delivered' | 'cancelled'
export type Order = {
    id: string
    customer: string
    address: string
    phone: string
    items: string[]
    total: number
    state: tOrderState
    cook?: string
    courier?: string
    ts: number
    history: {state: tOrderState, ts: number, by: string}[]
}
export type PizzeriaState = {
    accounts: Record<string, Account>
    menu: Record<string, MenuItem>
    orders: Record<string, Order>
}

/** The demo staff and their passwords — printed by the stand, seeded as HASHES. */
export const DEMO_LOGINS = {
    owner: 'owner-pass',
    manager: 'manager-pass',
    chef: 'chef-pass',
    rider: 'rider-pass',
    alice: 'alice-pass',
} as const

function account(name: string, phone: string, roles: tRole[], password: string): Account {
    return {account: name, name: name[0].toUpperCase() + name.slice(1), phone, roles, secret: hashSecret(password)}
}

const ACCOUNT_SHAPE = /^[a-z][a-z0-9_-]{2,31}$/

function transition(order: Order, from: tOrderState[], to: tOrderState, by: string) {
    if (!from.includes(order.state)) throw new Error(`order ${order.id} is ${order.state}, expected ${from.join(' or ')}`)
    order.state = to
    order.history.push({state: to, ts: Date.now(), by})
}

function requireOrder(state: PizzeriaState, orderId: string) {
    const order = state.orders[orderId]
    if (!order) throw new Error(`unknown order: ${orderId}`)
    return order
}

const day = (ts: number) => new Date(ts).toISOString().slice(0, 10)

// ============================================================
// the definition
// ============================================================

export const serviceDefinition = {
    name: 'pizzeria',
    storeId: 'pizzeria-store',
    originId: 'pizzeria-origin',
    initial: {
        accounts: {
            owner: account('owner', '+1-555-0100', ['owner', 'manager'], DEMO_LOGINS.owner),
            manager: account('manager', '+1-555-0101', ['manager'], DEMO_LOGINS.manager),
            chef: account('chef', '+1-555-0102', ['cook'], DEMO_LOGINS.chef),
            rider: account('rider', '+1-555-0103', ['courier'], DEMO_LOGINS.rider),
            alice: account('alice', '+1-555-0110', ['customer'], DEMO_LOGINS.alice),
        },
        menu: {
            margherita: {id: 'margherita', title: 'Margherita', price: 9, available: true},
            diavola: {id: 'diavola', title: 'Diavola', price: 12, available: true},
            calzone: {id: 'calzone', title: 'Calzone', price: 11, available: false},
        },
        orders: {},
    } as PizzeriaState,

    // ============== identity above the library: roles from state, credentials → account ==============
    access: {
        rolesOf: (state: PizzeriaState, who: string) => state.accounts[who]?.roles ?? [],
        login: {
            input: {account: 'string', password: 'string'},
            resolve(state: PizzeriaState, input: {account: string, password: string}) {
                return verifySecret(state.accounts[input.account]?.secret, input.password) ? input.account : null
            },
        },
        signup: {input: {account: 'string', name: 'string', phone: 'string', password: 'string'}, command: 'signup'},
    },

    // ============== commands: who may do what is `allow`, enforced twice ==============
    commands: {
        signup: schemaCommand({account: 'string', name: 'string', phone: 'string', password: 'string'}, {
            allow: ['system'],
            validate(input) {
                if (!ACCOUNT_SHAPE.test(input.account)) throw new Error('account must match ' + ACCOUNT_SHAPE)
                if (input.password.length < 6) throw new Error('password must be at least 6 characters')
            },
            apply(ctx: ServiceCommandCtx<PizzeriaState>, input) {
                if (ctx.state.accounts[input.account]) throw new Error(`account ${input.account} already exists`)
                ctx.state.accounts[input.account] = {
                    account: input.account, name: input.name, phone: input.phone, roles: ['customer'], secret: hashSecret(input.password),
                }
                return {account: input.account, name: input.name, roles: ['customer'] as tRole[]}
            },
        }),
        placeOrder: schemaCommand({items: {array: 'string'}, address: 'string'}, {
            allow: ['customer'],
            validate(input) {
                if (input.items.length == 0) throw new Error('an order needs at least one item')
                if (input.items.length > 20) throw new Error('at most 20 items per order')
            },
            apply(ctx: ServiceCommandCtx<PizzeriaState>, input) {
                let total = 0
                for (const itemId of input.items) {
                    const item = ctx.state.menu[itemId]
                    if (!item || !item.available) throw new Error(`${itemId} is not on the menu`)
                    total += item.price
                }
                const id = 'o-' + createHash('sha256').update(Command.commandReceiptKey(ctx.account, ctx.requestId)).digest('hex')
                if (Object.hasOwn(ctx.state.orders, id)) throw new Error('order request already used')
                const me = ctx.state.accounts[ctx.account]
                // Receipt scope prevents cross-account collisions; the digest keeps the tuple off the public ID.
                const order: Order = {
                    id, customer: ctx.account, address: input.address, phone: me?.phone ?? '',
                    items: [...input.items], total, state: 'placed', ts: Date.now(),
                    history: [{state: 'placed', ts: Date.now(), by: ctx.account}],
                }
                ctx.state.orders[order.id] = order
                return {...order}
            },
        }),
        cancelOrder: schemaCommand({orderId: 'string'}, {
            allow: ['customer'],
            apply(ctx: ServiceCommandCtx<PizzeriaState>, input) {
                const order = requireOrder(ctx.state, input.orderId)
                if (order.customer != ctx.account) throw new Error('only the customer who ordered may cancel')
                transition(order, ['placed'], 'cancelled', ctx.account)
                return {id: order.id, state: order.state}
            },
        }),
        startCooking: schemaCommand({orderId: 'string'}, {
            allow: ['cook'],
            apply(ctx: ServiceCommandCtx<PizzeriaState>, input) {
                const order = requireOrder(ctx.state, input.orderId)
                transition(order, ['placed'], 'cooking', ctx.account)
                order.cook = ctx.account
                return {id: order.id, state: order.state, cook: ctx.account}
            },
        }),
        markReady: schemaCommand({orderId: 'string'}, {
            allow: ['cook'],
            apply(ctx: ServiceCommandCtx<PizzeriaState>, input) {
                const order = requireOrder(ctx.state, input.orderId)
                if (order.cook != ctx.account) throw new Error('only the cook who started it may mark it ready')
                transition(order, ['cooking'], 'ready', ctx.account)
                return {id: order.id, state: order.state}
            },
        }),
        pickUp: schemaCommand({orderId: 'string'}, {
            allow: ['courier'],
            apply(ctx: ServiceCommandCtx<PizzeriaState>, input) {
                const order = requireOrder(ctx.state, input.orderId)
                transition(order, ['ready'], 'delivering', ctx.account)
                order.courier = ctx.account
                return {id: order.id, state: order.state, courier: ctx.account, address: order.address}
            },
        }),
        markDelivered: schemaCommand({orderId: 'string'}, {
            allow: ['courier'],
            apply(ctx: ServiceCommandCtx<PizzeriaState>, input) {
                const order = requireOrder(ctx.state, input.orderId)
                if (order.courier != ctx.account) throw new Error('only the courier who picked it up may deliver it')
                transition(order, ['delivering'], 'delivered', ctx.account)
                return {id: order.id, state: order.state, total: order.total}
            },
        }),
        setMenuItem: schemaCommand({id: 'string', title: 'string', price: 'number', available: 'boolean'}, {
            allow: ['manager', 'owner'],
            validate(input) {
                if (input.price < 0) throw new Error('price must not be negative')
            },
            apply(ctx: ServiceCommandCtx<PizzeriaState>, input) {
                ctx.state.menu[input.id] = {id: input.id, title: input.title, price: input.price, available: input.available}
                return {...ctx.state.menu[input.id]}
            },
        }),
        setRoles: schemaCommand({account: 'string', roles: {array: 'string'}}, {
            allow: ['owner'],
            validate(input) {
                for (const role of input.roles) if (!ROLES.includes(role as tRole)) throw new Error(`unknown role: ${role}`)
            },
            apply(ctx: ServiceCommandCtx<PizzeriaState>, input) {
                const target = ctx.state.accounts[input.account]
                if (!target) throw new Error(`unknown account: ${input.account}`)
                if (input.account == ctx.account && !input.roles.includes('owner')) throw new Error('an owner cannot drop the owner role')
                target.roles = [...new Set(input.roles as tRole[])]
                return {account: target.account, roles: [...target.roles]}
            },
        }),
    },

    // ============== views: what each audience reads, as its own line ==============
    views: {
        /** Anyone: the available menu. */
        menu: {
            allow: 'public', keys: ['menu'],
            project: (state: PizzeriaState) => ({
                items: Object.values(state.menu).filter(item => item.available).map(item => ({id: item.id, title: item.title, price: item.price})),
            }),
        },
        /** A customer: MY orders — one line per session, filtered by the principal. */
        myOrders: {
            allow: ['customer'], keys: ['orders'],
            project(state: PizzeriaState, principal: tServicePrincipal | null) {
                const orders: Record<string, Order> = {}
                for (const order of Object.values(state.orders)) if (order.customer == principal?.account) orders[order.id] = {...order}
                return {orders}
            },
        },
        /** The kitchen: open orders WITHOUT contacts — one line per process. */
        kitchen: {
            allow: ['cook', 'manager', 'owner'], shared: true, keys: ['orders'],
            project(state: PizzeriaState) {
                const orders: Record<string, {id: string, items: string[], state: tOrderState, cook?: string, ts: number}> = {}
                for (const order of Object.values(state.orders)) {
                    if (order.state != 'placed' && order.state != 'cooking' && order.state != 'ready') continue
                    orders[order.id] = {id: order.id, items: order.items, state: order.state, ...(order.cook ? {cook: order.cook} : {}), ts: order.ts}
                }
                return {orders}
            },
        },
        /** Dispatch: ready and delivering orders WITH the address and phone a courier needs. */
        dispatch: {
            allow: ['courier', 'manager', 'owner'], shared: true, keys: ['orders'],
            project(state: PizzeriaState) {
                const orders: Record<string, {id: string, address: string, phone: string, state: tOrderState, courier?: string}> = {}
                for (const order of Object.values(state.orders)) {
                    if (order.state != 'ready' && order.state != 'delivering') continue
                    orders[order.id] = {id: order.id, address: order.address, phone: order.phone, state: order.state, ...(order.courier ? {courier: order.courier} : {})}
                }
                return {orders}
            },
        },
        /** Staff: every account WITHOUT its secret. */
        staff: {
            allow: ['manager', 'owner'], shared: true, keys: ['accounts'],
            project(state: PizzeriaState) {
                const accounts: Record<string, {account: string, name: string, phone: string, roles: tRole[]}> = {}
                for (const entry of Object.values(state.accounts)) {
                    accounts[entry.account] = {account: entry.account, name: entry.name, phone: entry.phone, roles: [...entry.roles]}
                }
                return {accounts}
            },
        },
        /** The owner: delivered revenue by day. */
        revenue: {
            allow: ['owner'], shared: true, keys: ['orders'],
            project(state: PizzeriaState) {
                const byDay: Record<string, number> = {}
                let delivered = 0
                let total = 0
                for (const order of Object.values(state.orders)) {
                    if (order.state != 'delivered') continue
                    delivered++
                    total += order.total
                    byDay[day(order.ts)] = (byDay[day(order.ts)] ?? 0) + order.total
                }
                return {delivered, total, byDay}
            },
        },
    },
} satisfies tServiceDefinition<PizzeriaState>

export type PizzeriaDefinition = typeof serviceDefinition




