// Generated by scripts/generate-examples.mjs; edit the source in the repository.
// Shared HTTP resource; lifecycle tests exercise the public implementation.
export {createHostResource, type HostResource} from 'wenay-common2/service/host'
