// Generated by scripts/generate-examples.mjs; edit the source in the repository.
import {setTimeout as delay} from 'node:timers/promises'
import type {Ai} from 'wenay-common2'

export function createDemoProvider(deps: {stepMs?: number}) {
    const pending = new Map<string, AbortController>()
    async function run(context: Parameters<Ai.AiRunRunner['run']>[0]) {
        const controller = new AbortController()
        pending.set(context.run.id, controller)
        try {
            const ticket = (context.input as {ticket: string}).ticket.trim()
            context.report({progress: 0.15, message: 'Demo: reading the pasted ticket'})
            await delay(deps.stepMs ?? 400, undefined, {signal: controller.signal})
            if (context.cancelled()) return
            const category = /invoice|refund|payment|bill/i.test(ticket) ? 'billing' : /login|password|access/i.test(ticket) ? 'access' : 'general'
            context.report({progress: 0.55, message: 'Demo: matching simple category rules'})
            context.emit({type: 'text.delta', text: 'Template category: ' + category})
            await delay(deps.stepMs ?? 400, undefined, {signal: controller.signal})
            if (context.cancelled()) return
            context.report({progress: 0.9, message: 'Demo: assembling a reply template'})
            await delay(deps.stepMs ?? 400, undefined, {signal: controller.signal})
            if (context.cancelled()) return
            return {result: {
                provider: 'demo, no AI model', summary: ticket.slice(0, 200), category,
                draft: `Thank you for contacting support about ${category}. We have received your request and will review the details. Please share any relevant reference number.`,
            }}
        } catch (error) {
            if (!controller.signal.aborted) throw error
        } finally { pending.delete(context.run.id) }
    }
    function cancel({run}: Parameters<NonNullable<Ai.AiRunRunner['cancel']>>[0]) { pending.get(run.id)?.abort() }
    return {run, cancel} satisfies Ai.AiRunRunner
}
