// =====================================================================
// AI run host — authorized lifecycle + resumable semantic events
// =====================================================================
// The host deliberately owns protocol state, not a model provider. Providers
// receive opaque input and resource ids; bytes, credentials and raw reasoning
// stay in the application adapter behind the runner port.

import {createStore, StoreChange, StoreDrain} from '../Observe/store'
import {exposeStoreReplay} from '../Observe/store-replay'
import {
    cloneStoreProjectionValue,
    collectStoreProjectionChanges,
    reconcileStoreProjection,
    reconcileStoreProjectionRecord,
} from '../Observe/store-projection'
import {listen as createListenPair} from '../events/Listen'
import {exposeReplay} from '../events/replay-wire'
import {replayListen} from '../events/replay-listen'

export type AiRunState = 'queued' | 'running' | 'waiting_input' | 'waiting_approval' | 'completed' | 'failed' | 'cancelled'
export type AiApprovalState = 'pending' | 'approved' | 'rejected' | 'cancelled'
export type AiInputState = 'waiting' | 'provided' | 'cancelled'

export type AiRunUsage = {
    inputTokens?: number
    outputTokens?: number
    totalTokens?: number
}

/** Small output descriptor. Put large generated bytes in Resource storage instead. */
export type AiArtifact = {
    id: string
    kind: string
    label?: string
    resourceId?: string
    descriptor?: unknown
}

export type AiRun = {
    id: string
    owner: string
    requestId: string
    kind: string
    resourceIds: string[]
    state: AiRunState
    progress: number
    message?: string
    result?: unknown
    artifacts: AiArtifact[]
    usage?: AiRunUsage
    error?: string
    createdAt: number
    updatedAt: number
}

export type AiRunApproval = {
    id: string
    runId: string
    kind: string
    label: string
    data?: unknown
    state: AiApprovalState
    createdAt: number
    updatedAt: number
}

/** Request metadata is public to authorized viewers; the supplied value stays only in the runner call. */
export type AiRunInput = {
    id: string
    runId: string
    label: string
    schema?: unknown
    state: AiInputState
    createdAt: number
    updatedAt: number
}

export type AiRunStore = {
    runs: Record<string, AiRun>
    approvals: Record<string, AiRunApproval>
    inputs: Record<string, AiRunInput>
}

export type AiCapability = {
    kind: string
    label?: string
    inputSchema?: unknown
    acceptsResources?: boolean
}

export type AiRunRequest = {
    /** Owner-scoped retry key. Repeating it returns the first run and never starts the model twice. */
    requestId: string
    kind: string
    input: unknown
    resourceIds?: string[]
}

export type AiRunReport = {
    progress?: number
    message?: string
    usage?: AiRunUsage
}

export type AiArtifactInput = Omit<AiArtifact, 'id'> & {id?: string}

export type AiRunLiveEvent =
    | {type: 'text.delta', text: string}
    | {type: 'notice', message: string, data?: unknown}
    | {type: 'tool.call', callId: string, name: string, input?: unknown}
    | {type: 'tool.result', callId: string, result?: unknown}

export type AiRunEvent =
    | {type: 'sync', runs: AiRun[], approvals: AiRunApproval[], inputs: AiRunInput[]}
    | ({runId: string} & (
        | AiRunLiveEvent
        | {type: 'started'}
        | {type: 'progress', progress: number, message?: string, usage?: AiRunUsage}
        | {type: 'artifact', artifact: AiArtifact}
        | {type: 'approval.requested', approval: AiRunApproval}
        | {type: 'approval.resolved', approval: AiRunApproval}
        | {type: 'input.requested', input: AiRunInput}
        | {type: 'input.provided', input: AiRunInput}
        | {type: 'completed', result?: unknown, usage?: AiRunUsage}
        | {type: 'failed', error: string}
        | {type: 'cancelled', reason?: string}
    ))

export type AiRunOutput = {
    result?: unknown
    usage?: AiRunUsage
}

export type AiRunRunner = {
    run(input: {
        run: AiRun
        input: unknown
        resourceIds: string[]
        report: (next: AiRunReport) => void
        emit: (event: AiRunLiveEvent) => void
        artifact: (artifact: AiArtifactInput) => AiArtifact | undefined
        requestApproval: (request: {kind: string, label: string, data?: unknown}) => Promise<'approved' | 'rejected'>
        waitForInput: (request: {label: string, schema?: unknown}) => Promise<unknown>
        cancelled: () => boolean
    }): AiRunOutput | void | Promise<AiRunOutput | void>
    /** Optional provider abort. The host still ignores late reports and results unconditionally. */
    cancel?(input: {run: AiRun, reason?: string}): void | Promise<void>
}

export type AiRunPolicy = {
    /** Default: an account sees only its own runs and their related state/events. */
    canRead?: (account: string, run: AiRun) => boolean
    /** Default: only the owner may cancel or resolve an input/approval. */
    canWrite?: (account: string, run: AiRun) => boolean
    /** Use for quota, entitlement or tenant checks before a run exists. */
    canCreate?: (account: string, request: AiRunRequest) => boolean
}

export type AiRunHostDeps = {
    runner: AiRunRunner
    capabilities?: AiCapability[]
    policy?: AiRunPolicy
    id?: () => string
    now?: () => number
    history?: number
    drain?: StoreDrain
}

type AiRunView = {
    refresh: (change: StoreChange) => void
    close: () => void
}

type PendingWaiter = {
    resolve: (value: any) => void
    reject: (error: Error) => void
}

function errorText(error: unknown) {
    return error instanceof Error ? error.message : String(error)
}

function clampProgress(value: number) {
    return Math.max(0, Math.min(1, value))
}

function copyUsage(usage: AiRunUsage | undefined) {
    return usage ? {...usage} : undefined
}

function copyArtifact(artifact: AiArtifact) {
    return {
        ...artifact,
        ...(artifact.descriptor !== undefined ? {descriptor: cloneStoreProjectionValue(artifact.descriptor)} : {}),
    }
}

function copyRun(run: AiRun): AiRun {
    return {
        ...run,
        resourceIds: [...run.resourceIds],
        artifacts: run.artifacts.map(copyArtifact),
        usage: copyUsage(run.usage),
        ...(run.result !== undefined ? {result: cloneStoreProjectionValue(run.result)} : {}),
    }
}

function copyApproval(approval: AiRunApproval) {
    return {
        ...approval,
        ...(approval.data !== undefined ? {data: cloneStoreProjectionValue(approval.data)} : {}),
    }
}

function copyInput(input: AiRunInput) {
    return {
        ...input,
        ...(input.schema !== undefined ? {schema: cloneStoreProjectionValue(input.schema)} : {}),
    }
}

function terminal(state: AiRunState) {
    return state == 'completed' || state == 'failed' || state == 'cancelled'
}

export function createAiRunHost(deps: AiRunHostDeps) {
    const {runner, policy, history, drain, now = Date.now} = deps
    const capabilities = [...(deps.capabilities ?? [])]
    let nextId = 0
    const makeId = deps.id ?? function defaultId() { return 'ai-' + (++nextId) }
    const store = createStore<AiRunStore>({runs: {}, approvals: {}, inputs: {}}, drain !== undefined ? {drain} : {})
    const views = new Set<AiRunView>()
    const requestIds = new Map<string, string>()
    const cancelled = new Set<string>()
    const approvalWaiters = new Map<string, PendingWaiter>()
    const inputWaiters = new Map<string, PendingWaiter>()
    const [emitEvent, eventLine] = createListenPair<[AiRunEvent]>()
    let closed = false

    // === Business policy ===

    function readable(account: string, run: AiRun) {
        return policy?.canRead ? policy.canRead(account, run) : run.owner == account
    }

    function writable(account: string, run: AiRun) {
        return policy?.canWrite ? policy.canWrite(account, run) : run.owner == account
    }

    function requireRun(account: string, runId: string, action: string) {
        const run = store.state.runs[runId]
        if (!run || !writable(account, run)) throw new Error('AI run ' + action + ': forbidden or missing')
        return run
    }

    function project(account: string): AiRunStore {
        const runs: Record<string, AiRun> = {}
        const approvals: Record<string, AiRunApproval> = {}
        const inputs: Record<string, AiRunInput> = {}
        for (const [id, run] of Object.entries(store.state.runs)) {
            if (readable(account, run)) runs[id] = copyRun(run)
        }
        for (const [id, approval] of Object.entries(store.state.approvals)) {
            if (runs[approval.runId]) approvals[id] = copyApproval(approval)
        }
        for (const [id, input] of Object.entries(store.state.inputs)) {
            if (runs[input.runId]) inputs[id] = copyInput(input)
        }
        return {runs, approvals, inputs}
    }

    function syncEvent(account: string): AiRunEvent {
        const state = project(account)
        return {
            type: 'sync',
            runs: Object.values(state.runs),
            approvals: Object.values(state.approvals),
            inputs: Object.values(state.inputs),
        }
    }

    function refreshViews(change: StoreChange) {
        if (closed) return
        for (const view of views) view.refresh(change)
    }

    const offStore = store.listenPaths().on(refreshViews)

    function createView(account: string) {
        const state = createStore<AiRunStore>(project(account), drain !== undefined ? {drain} : {})
        const stateReplay = exposeStoreReplay(state, history == undefined ? {} : {history})
        const [emitViewEvent, events] = replayListen<[AiRunEvent]>({
            current: () => [syncEvent(account)],
            history: history ?? 1024,
        })
        const offEvents = eventLine.on(function forwardReadableEvent(event) {
            if (event.type == 'sync') return
            const run = store.state.runs[event.runId]
            if (run && readable(account, run)) emitViewEvent(event)
        })
        function refreshApproval(id: string) {
            const approval = store.state.approvals[id]
            const visible = !!approval && !!state.state.runs[approval.runId]
            reconcileStoreProjectionRecord(state, 'approvals', id, {
                exists: visible,
                ...(visible ? {value: copyApproval(approval!)} : {}),
            })
        }
        function refreshInput(id: string) {
            const input = store.state.inputs[id]
            const visible = !!input && !!state.state.runs[input.runId]
            reconcileStoreProjectionRecord(state, 'inputs', id, {
                exists: visible,
                ...(visible ? {value: copyInput(input!)} : {}),
            })
        }
        function refreshRun(id: string) {
            const run = store.state.runs[id]
            const wasVisible = !!state.state.runs[id]
            const visible = !!run && readable(account, run)
            reconcileStoreProjectionRecord(state, 'runs', id, {
                exists: visible,
                ...(visible ? {value: copyRun(run!)} : {}),
            })
            if (visible == wasVisible) return
            const approvals = visible ? store.state.approvals : state.state.approvals
            const inputs = visible ? store.state.inputs : state.state.inputs
            for (const approval of Object.values(approvals)) if (approval.runId == id) refreshApproval(approval.id)
            for (const input of Object.values(inputs)) if (input.runId == id) refreshInput(input.id)
        }
        function refreshProjection(change: StoreChange) {
            // A custom policy may close over tenant membership outside the changed record.
            if (policy?.canRead) { reconcileStoreProjection(state, project(account)); return }
            const changed = collectStoreProjectionChanges(change, ['runs', 'approvals', 'inputs'])
            if (!changed) { reconcileStoreProjection(state, project(account)); return }
            for (const id of changed.get('runs') ?? []) refreshRun(String(id))
            for (const id of changed.get('approvals') ?? []) refreshApproval(String(id))
            for (const id of changed.get('inputs') ?? []) refreshInput(String(id))
        }
        let view: AiRunView
        view = {
            refresh: refreshProjection,
            close() {
                views.delete(view)
                offEvents()
                stateReplay.close()
                events.close()
            },
        }
        return {view, stateReplay, events}
    }

    // === Lifecycle helpers ===

    function touchRun(run: AiRun) {
        run.updatedAt = now()
    }

    function touchApproval(approval: AiRunApproval) {
        approval.updatedAt = now()
    }

    function touchInput(input: AiRunInput) {
        input.updatedAt = now()
    }

    function active(run: AiRun | undefined) {
        return !!run && !closed && !cancelled.has(run.id) && !terminal(run.state)
    }

    function emitRunEvent(event: Exclude<AiRunEvent, {type: 'sync'}>) {
        const run = store.state.runs[event.runId]
        if (!run || closed) return
        // Replay/event consumers own their message, never the authority's
        // retained result, descriptor or policy-visible Store value.
        emitEvent(cloneStoreProjectionValue(event) as Exclude<AiRunEvent, {type: 'sync'}>)
    }

    function refreshWaitingState(run: AiRun) {
        if (terminal(run.state)) return
        const waitingApproval = Object.values(store.state.approvals).some(approval => approval.runId == run.id && approval.state == 'pending')
        const waitingInput = Object.values(store.state.inputs).some(input => input.runId == run.id && input.state == 'waiting')
        const next: AiRunState = waitingApproval ? 'waiting_approval' : waitingInput ? 'waiting_input' : 'running'
        if (run.state != next) {
            run.state = next
            touchRun(run)
        }
    }

    function cancelPendingWaiters(run: AiRun, reason: string) {
        for (const approval of Object.values(store.state.approvals)) {
            if (approval.runId != run.id || approval.state != 'pending') continue
            approval.state = 'cancelled'
            touchApproval(approval)
            approvalWaiters.get(approval.id)?.reject(new Error(reason))
            approvalWaiters.delete(approval.id)
        }
        for (const input of Object.values(store.state.inputs)) {
            if (input.runId != run.id || input.state != 'waiting') continue
            input.state = 'cancelled'
            touchInput(input)
            inputWaiters.get(input.id)?.reject(new Error(reason))
            inputWaiters.delete(input.id)
        }
    }

    function requestProviderCancel(run: AiRun, reason?: string) {
        if (!runner.cancel) return
        Promise.resolve(runner.cancel({run: copyRun(run), reason})).catch(function ignoreProviderCancelFailure() {})
    }

    function reportRun(runId: string, next: AiRunReport) {
        const run = store.state.runs[runId]
        if (!active(run)) return
        if (next.progress != null) {
            if (!Number.isFinite(next.progress)) throw new Error('AI run progress must be finite')
            run.progress = clampProgress(next.progress)
        }
        if (next.message != null) run.message = next.message
        if (next.usage != null) run.usage = copyUsage(next.usage)
        touchRun(run)
        emitRunEvent({runId, type: 'progress', progress: run.progress, ...(run.message != null ? {message: run.message} : {}), ...(run.usage ? {usage: copyUsage(run.usage)!} : {})})
    }

    function emitLiveEvent(runId: string, event: AiRunLiveEvent) {
        const run = store.state.runs[runId]
        if (!active(run)) return
        emitRunEvent({runId, ...event} as Exclude<AiRunEvent, {type: 'sync'}>)
    }

    function addArtifact(runId: string, input: AiArtifactInput) {
        const run = store.state.runs[runId]
        if (!active(run)) return undefined
        if (!input || typeof input.kind != 'string' || !input.kind.trim()) throw new Error('AI artifact kind is required')
        const artifact: AiArtifact = {
            ...input,
            id: input.id ?? makeId(),
            kind: input.kind,
            ...(input.descriptor !== undefined ? {descriptor: cloneStoreProjectionValue(input.descriptor)} : {}),
        }
        run.artifacts.push(artifact)
        touchRun(run)
        emitRunEvent({runId, type: 'artifact', artifact: copyArtifact(artifact)})
        return copyArtifact(artifact)
    }

    function requestApproval(runId: string, request: {kind: string, label: string, data?: unknown}) {
        const run = store.state.runs[runId]
        if (!active(run)) return Promise.reject(new Error('AI run approval: run is not active'))
        if (!request || typeof request.kind != 'string' || !request.kind.trim()) return Promise.reject(new Error('AI run approval: kind is required'))
        if (typeof request.label != 'string' || !request.label.trim()) return Promise.reject(new Error('AI run approval: label is required'))
        const createdAt = now()
        const approval: AiRunApproval = {
            id: makeId(), runId, kind: request.kind, label: request.label, state: 'pending', createdAt, updatedAt: createdAt,
            ...(request.data !== undefined ? {data: cloneStoreProjectionValue(request.data)} : {}),
        }
        store.state.approvals[approval.id] = approval
        refreshWaitingState(run)
        const waiting = new Promise<'approved' | 'rejected'>(function waitForApproval(resolve, reject) {
            approvalWaiters.set(approval.id, {resolve, reject})
        })
        // Direct and in-process consumers may answer from the event callback itself.
        // Register first so that synchronous resolution cannot outrun the waiter.
        emitRunEvent({runId, type: 'approval.requested', approval: copyApproval(approval)})
        return waiting
    }

    function waitForInput(runId: string, request: {label: string, schema?: unknown}) {
        const run = store.state.runs[runId]
        if (!active(run)) return Promise.reject(new Error('AI run input: run is not active'))
        if (!request || typeof request.label != 'string' || !request.label.trim()) return Promise.reject(new Error('AI run input: label is required'))
        const createdAt = now()
        const input: AiRunInput = {
            id: makeId(), runId, label: request.label, state: 'waiting', createdAt, updatedAt: createdAt,
            ...(request.schema !== undefined ? {schema: cloneStoreProjectionValue(request.schema)} : {}),
        }
        store.state.inputs[input.id] = input
        refreshWaitingState(run)
        const waiting = new Promise<unknown>(function waitForProvidedInput(resolve, reject) {
            inputWaiters.set(input.id, {resolve, reject})
        })
        emitRunEvent({runId, type: 'input.requested', input: copyInput(input)})
        return waiting
    }

    async function executeRun(runId: string, request: AiRunRequest) {
        const run = store.state.runs[runId]
        if (!active(run)) return
        run.state = 'running'
        touchRun(run)
        emitRunEvent({runId, type: 'started'})
        try {
            const output = await runner.run({
                run: copyRun(run),
                input: request.input,
                resourceIds: [...run.resourceIds],
                report: next => reportRun(runId, next),
                emit: event => emitLiveEvent(runId, event),
                artifact: artifact => addArtifact(runId, artifact),
                requestApproval: approval => requestApproval(runId, approval),
                waitForInput: input => waitForInput(runId, input),
                cancelled: () => cancelled.has(runId) || closed,
            })
            const current = store.state.runs[runId]
            if (!active(current)) return
            cancelPendingWaiters(current, 'AI run completed before its response arrived')
            current.state = 'completed'
            current.progress = 1
            if (output?.result !== undefined) current.result = cloneStoreProjectionValue(output.result)
            if (output?.usage !== undefined) current.usage = copyUsage(output.usage)
            touchRun(current)
            emitRunEvent({runId, type: 'completed', ...(current.result !== undefined ? {result: current.result} : {}), ...(current.usage ? {usage: copyUsage(current.usage)!} : {})})
        } catch (error) {
            const current = store.state.runs[runId]
            if (!current || cancelled.has(runId) || closed || current.state == 'cancelled') return
            cancelPendingWaiters(current, 'AI run failed before its response arrived')
            current.state = 'failed'
            current.error = errorText(error)
            touchRun(current)
            emitRunEvent({runId, type: 'failed', error: current.error})
        }
    }

    // === RPC commands ===

    function getCapabilities() {
        return capabilities.map(capability => ({...capability}))
    }

    function createRun(account: string, request: AiRunRequest) {
        if (closed) throw new Error('AI run host closed')
        if (!request || typeof request.requestId != 'string' || !request.requestId.trim()) throw new Error('AI run create: requestId is required')
        if (typeof request.kind != 'string' || !request.kind.trim()) throw new Error('AI run create: kind is required')
        if (policy?.canCreate && !policy.canCreate(account, request)) throw new Error('AI run create: forbidden')
        const requestKey = account + '\u0000' + request.requestId
        const previous = requestIds.get(requestKey)
        if (previous) {
            const existing = store.state.runs[previous]
            if (existing) return copyRun(existing)
        }
        if (capabilities.length && !capabilities.some(capability => capability.kind == request.kind)) {
            throw new Error('AI run create: unsupported kind ' + request.kind)
        }
        const createdAt = now()
        const run: AiRun = {
            id: makeId(), owner: account, requestId: request.requestId, kind: request.kind,
            resourceIds: [...(request.resourceIds ?? [])], state: 'queued', progress: 0, artifacts: [],
            createdAt, updatedAt: createdAt,
        }
        requestIds.set(requestKey, run.id)
        store.state.runs[run.id] = run
        void executeRun(run.id, request)
        return copyRun(run)
    }

    function cancelRun(account: string, runId: string, reason?: string) {
        const run = requireRun(account, runId, 'cancel')
        if (terminal(run.state)) return copyRun(run)
        cancelled.add(run.id)
        cancelPendingWaiters(run, reason ?? 'AI run cancelled')
        run.state = 'cancelled'
        run.message = reason ?? 'cancelled'
        touchRun(run)
        emitRunEvent({runId: run.id, type: 'cancelled', ...(reason ? {reason} : {})})
        requestProviderCancel(run, reason)
        return copyRun(run)
    }

    function resolveApproval(account: string, approvalId: string, decision: 'approved' | 'rejected') {
        const approval = store.state.approvals[approvalId]
        const run = approval && store.state.runs[approval.runId]
        if (!approval || !run || !writable(account, run)) throw new Error('AI approval resolve: forbidden or missing')
        if (decision != 'approved' && decision != 'rejected') throw new Error('AI approval resolve: invalid decision')
        if (approval.state != 'pending') return copyApproval(approval)
        approval.state = decision
        touchApproval(approval)
        refreshWaitingState(run)
        emitRunEvent({runId: run.id, type: 'approval.resolved', approval: copyApproval(approval)})
        approvalWaiters.get(approval.id)?.resolve(decision)
        approvalWaiters.delete(approval.id)
        return copyApproval(approval)
    }

    function provideInput(account: string, inputId: string, value: unknown) {
        const input = store.state.inputs[inputId]
        const run = input && store.state.runs[input.runId]
        if (!input || !run || !writable(account, run)) throw new Error('AI input provide: forbidden or missing')
        if (input.state != 'waiting') return copyInput(input)
        input.state = 'provided'
        touchInput(input)
        refreshWaitingState(run)
        emitRunEvent({runId: run.id, type: 'input.provided', input: copyInput(input)})
        inputWaiters.get(input.id)?.resolve(cloneStoreProjectionValue(value))
        inputWaiters.delete(input.id)
        return copyInput(input)
    }

    function connection(account: string) {
        if (closed) throw new Error('AI run host closed')
        const {view, stateReplay, events} = createView(account)
        views.add(view)
        let connectionClosed = false
        return {
            fragment: {
                capabilities: getCapabilities,
                state: stateReplay.api.replay,
                events: exposeReplay(events),
                createRun: (request: AiRunRequest) => createRun(account, request),
                cancelRun: (runId: string, reason?: string) => cancelRun(account, runId, reason),
                resolveApproval: (approvalId: string, decision: 'approved' | 'rejected') => resolveApproval(account, approvalId, decision),
                provideInput: (inputId: string, value: unknown) => provideInput(account, inputId, value),
            },
            close() {
                if (connectionClosed) return
                connectionClosed = true
                view.close()
            },
        }
    }

    return {
        connection,
        /** Server-only authority. Expose only the account-filtered `connection(account).fragment`. */
        store,
        close() {
            if (closed) return
            closed = true
            offStore()
            for (const run of Object.values(store.state.runs)) {
                if (!terminal(run.state)) requestProviderCancel(run, 'AI run host closed')
            }
            for (const waiter of approvalWaiters.values()) waiter.reject(new Error('AI run host closed'))
            for (const waiter of inputWaiters.values()) waiter.reject(new Error('AI run host closed'))
            approvalWaiters.clear()
            inputWaiters.clear()
            for (const view of Array.from(views)) view.close()
            eventLine.close()
            cancelled.clear()
        },
    }
}

export type AiRunHost = ReturnType<typeof createAiRunHost>
