"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.__LineFiles = exports.__LineFile2 = exports.__LineFile = exports.callerLines = exports.callerLine = exports.disable = exports.enable = exports.installConsoleCallerAnnotations = void 0;
var node_console_1 = require("./Common/node_console");
Object.defineProperty(exports, "installConsoleCallerAnnotations", { enumerable: true, get: function () { return node_console_1.installConsoleCallerAnnotations; } });
Object.defineProperty(exports, "enable", { enumerable: true, get: function () { return node_console_1.enable; } });
Object.defineProperty(exports, "disable", { enumerable: true, get: function () { return node_console_1.disable; } });
Object.defineProperty(exports, "callerLine", { enumerable: true, get: function () { return node_console_1.callerLine; } });
Object.defineProperty(exports, "callerLines", { enumerable: true, get: function () { return node_console_1.callerLines; } });
Object.defineProperty(exports, "__LineFile", { enumerable: true, get: function () { return node_console_1.__LineFile; } });
Object.defineProperty(exports, "__LineFile2", { enumerable: true, get: function () { return node_console_1.__LineFile2; } });
Object.defineProperty(exports, "__LineFiles", { enumerable: true, get: function () { return node_console_1.__LineFiles; } });
