// Generated by scripts/generate-examples.mjs; edit the source in the repository.
import {runLeaderProcess} from './leader'
import {DEMO_LOGINS, serviceDefinition} from './service'

runLeaderProcess({definition: serviceDefinition, mount({url}) {
    setTimeout(function logAccounts() {
        console.log(`[small-jobs] ${url()}/panel — ` + Object.entries(DEMO_LOGINS).map(([account, password]) => `${account}/${password}`).join(', '))
    }, 0)
}}).catch(function fatal(error) { console.error(error); process.exit(2) })
