// Generated by scripts/generate-examples.mjs; edit the source in the repository.
// Compatibility path; the implementation is owned by the public service runtime.
export * from 'wenay-common2/service/server'
export * from 'wenay-common2/service'
export * from 'wenay-common2/service/host'
import {runNodeProcess} from 'wenay-common2/service/host'

if (require.main == module) {
    import('./service.js').then(function run({serviceDefinition}) {
        return runNodeProcess({definition: serviceDefinition})
    }).catch(function fatal(error) { console.error(error); process.exitCode = 2 })
}
