// Generated by scripts/generate-examples.mjs; edit the source in the repository.
// =====================================================================
// apartments — the domain module: bookings, payments as intents, a lock device
// =====================================================================
// The ONLY authored file of the service. Three audiences plus the host
// process itself:
//   guest   — books an apartment, pays (an intent the effects runner performs),
//             sees the access code once the lock armed it, unlocks from the app
//   host    — lists apartments, sees bookings with guests, payments, lock health
//   device  — a lock: follows ITS OWN command line, executes, reports back
//   system  — the leader: settles payments (webhook), records effect outcomes
// Two rules carry the whole example:
//   - a command never calls the outside world: it records an INTENT (a payment
//     to charge, a lock command to execute) and someone else performs it and
//     reports the outcome as another command — so every external step is a
//     replicated, archived fact with an idempotent requestId;
//   - a device is a principal like any other: its own account, role 'device',
//     its own view line (only its lock), its own allow list.

import {createHash, randomInt} from 'node:crypto'
import {Command} from 'wenay-common2'
import {schemaCommand} from './input-schema'
import type {ServiceCommandCtx, tServiceDefinition, tServicePrincipal} from './leader'
import {hashSecret, verifySecret, type tSecret} from './identity'
import {LOCK_UNLOCK_TTL_MS, lockCommandExpiresAt, lockCommandIsCurrent} from './lock-policy'

// ============================================================
// state
// ============================================================

export const ROLES = ['guest', 'host', 'device'] as const
export type tRole = typeof ROLES[number]

export type Account = {account: string, name: string, roles: tRole[], secret: tSecret}
export type Apartment = {id: string, title: string, host: string, pricePerNight: number, lockId: string}
export type tBookingState = 'pending' | 'paid' | 'declined' | 'cancelled'
export type Booking = {
    id: string
    apartmentId: string
    guest: string
    from: string
    to: string
    nights: number
    total: number
    state: tBookingState
    paymentId: string
    /** The door code, minted on settlement; shown to the guest once the lock reports it armed. */
    code?: string
    codeArmed: boolean
    ts: number
}
export type tPaymentState = 'pending' | 'submitted' | 'confirmed' | 'failed'
/** A payment INTENT: pending until the runner charged it, settled by the provider's webhook. */
export type Payment = {id: string, bookingId: string, amount: number, currency: string, state: tPaymentState, ref?: string, error?: string, ts: number}
export type tLockCommandKind = 'setCode' | 'clearCode' | 'unlock'
export type LockCommand = {id: string, kind: tLockCommandKind, code?: string, bookingId?: string, requestedBy: string, state: 'pending' | 'done' | 'failed', detail?: string, ts: number, expiresAt?: number}
export type LockEvent = {ts: number, kind: string, detail?: string}
/** What the provider told us, verbatim enough to audit: one record per verified webhook event. */
export type PaymentEvent = {id: string, ts: number, paymentId: string, status: 'confirmed' | 'failed', ref?: string, error?: string, applied: boolean}
export type Lock = {id: string, apartmentId: string, device: string, online: boolean, battery?: number, seenAt?: number, commands: Record<string, LockCommand>, events: LockEvent[]}
export type ApartmentsState = {
    accounts: Record<string, Account>
    apartments: Record<string, Apartment>
    bookings: Record<string, Booking>
    payments: Record<string, Payment>
    /** The tracking ledger: every verified provider event, applied or not. */
    events: Record<string, PaymentEvent>
    locks: Record<string, Lock>
}

/** The demo principals and their passwords — the lock's password is the DEVICE secret. */
export const DEMO_LOGINS = {anna: 'anna-pass', bob: 'bob-pass', 'lock-1': 'lock-1-secret'} as const
export const CURRENCY = 'EUR'

function account(name: string, roles: tRole[], password: string): Account {
    return {account: name, name: name[0].toUpperCase() + name.slice(1), roles, secret: hashSecret(password)}
}
const ACCOUNT_SHAPE = /^[a-z][a-z0-9_-]{2,31}$/
const ISO_DAY = /^\d{4}-\d{2}-\d{2}$/
const today = () => new Date().toISOString().slice(0, 10)
const nightsBetween = (from: string, to: string) => Math.round((Date.parse(to) - Date.parse(from)) / 86_400_000)
/** Half-open spans [from, to): ISO days compare correctly as strings. */
const overlaps = (a: {from: string, to: string}, b: {from: string, to: string}) => a.from < b.to && b.from < a.to
const holdsDates = (booking: Booking) => booking.state == 'pending' || booking.state == 'paid'

// Public IDs retain receipt scope without exposing the account/request tuple.
function opaqueRequestId(ctx: ServiceCommandCtx<ApartmentsState>) {
    return createHash('sha256').update(Command.commandReceiptKey(ctx.account, ctx.requestId)).digest('hex')
}

function requireBooking(state: ApartmentsState, id: string) {
    const booking = state.bookings[id]
    if (!booking) throw new Error(`unknown booking: ${id}`)
    return booking
}
function requirePayment(state: ApartmentsState, id: string) {
    const payment = state.payments[id]
    if (!payment) throw new Error(`unknown payment: ${id}`)
    return payment
}
function lockOfDevice(state: ApartmentsState, device: string) {
    const lock = Object.values(state.locks).find(candidate => candidate.device == device)
    if (!lock) throw new Error(`no lock is bound to device ${device}`)
    return lock
}
function pushEvent(lock: Lock, kind: string, detail?: string) {
    lock.events.push({ts: Date.now(), kind, ...(detail ? {detail} : {})})
    if (lock.events.length > 50) lock.events.splice(0, lock.events.length - 50)
}
/** A projection removes stale work without pretending a late physical outcome did not happen. */
function currentLockCommand(state: ApartmentsState, lock: Lock, command: LockCommand, now: number) {
    if (command.state != 'pending') return null
    if (command.kind == 'clearCode') return lockCommandIsCurrent(command, now) ? {...command} : null
    const booking = state.bookings[command.bookingId ?? '']
    if (!booking || booking.state != 'paid' || booking.apartmentId != lock.apartmentId) return null
    if (command.kind == 'unlock' && (booking.guest != command.requestedBy || now < Date.parse(booking.from))) return null
    if (command.kind == 'setCode' && (!booking.code || command.code != booking.code)) return null
    const bounded = {...command, expiresAt: Math.min(Date.parse(booking.to), command.expiresAt ?? Infinity)}
    if (!lockCommandIsCurrent(bounded, now)) return null
    return {...bounded, expiresAt: lockCommandExpiresAt(bounded)!}
}
/** Record a lock INTENT; the device performs it and reports through lockReport. */
function enqueueLockCommand(lock: Lock, id: string, command: Omit<LockCommand, 'id' | 'state' | 'ts'>) {
    if (lock.commands[id]) return lock.commands[id]
    lock.commands[id] = {id, ...command, state: 'pending', ts: Date.now()}
    return lock.commands[id]
}

// ============================================================
// the definition
// ============================================================

export const serviceDefinition = {
    name: 'apartments',
    storeId: 'apartments-store',
    originId: 'apartments-origin',
    initial: {
        accounts: {
            anna: account('anna', ['host'], DEMO_LOGINS.anna),
            bob: account('bob', ['guest'], DEMO_LOGINS.bob),
            'lock-1': account('lock-1', ['device'], DEMO_LOGINS['lock-1']),
        },
        apartments: {
            'loft-1': {id: 'loft-1', title: 'Riverside loft', host: 'anna', pricePerNight: 120, lockId: 'lock-1'},
        },
        bookings: {},
        payments: {},
        events: {},
        locks: {
            'lock-1': {id: 'lock-1', apartmentId: 'loft-1', device: 'lock-1', online: false, commands: {}, events: []},
        },
    } as ApartmentsState,

    // ============== identity above the library: roles from state, one login for people AND devices ==============
    access: {
        rolesOf: (state: ApartmentsState, who: string) => state.accounts[who]?.roles ?? [],
        login: {
            input: {account: 'string', password: 'string'},
            resolve(state: ApartmentsState, input: {account: string, password: string}) {
                return verifySecret(state.accounts[input.account]?.secret, input.password) ? input.account : null
            },
        },
        signup: {input: {account: 'string', name: 'string', password: 'string'}, command: 'signup'},
    },

    // ============== commands ==============
    commands: {
        signup: schemaCommand({account: 'string', name: 'string', password: 'string'}, {
            allow: ['system'],
            validate(input) {
                if (!ACCOUNT_SHAPE.test(input.account)) throw new Error('account must match ' + ACCOUNT_SHAPE)
                if (input.password.length < 6) throw new Error('password must be at least 6 characters')
            },
            apply(ctx: ServiceCommandCtx<ApartmentsState>, input) {
                if (ctx.state.accounts[input.account]) throw new Error(`account ${input.account} already exists`)
                ctx.state.accounts[input.account] = {account: input.account, name: input.name, roles: ['guest'], secret: hashSecret(input.password)}
                return {account: input.account, roles: ['guest'] as tRole[]}
            },
        }),
        /** A host adds an apartment WITH its lock: the device gets an account of role 'device' bound to the lock. */
        addApartment: schemaCommand({id: 'string', title: 'string', pricePerNight: 'number', lockId: 'string', devicePassword: 'string'}, {
            allow: ['host'],
            validate(input) {
                if (!ACCOUNT_SHAPE.test(input.id) || !ACCOUNT_SHAPE.test(input.lockId)) throw new Error('ids must match ' + ACCOUNT_SHAPE)
                if (input.pricePerNight <= 0) throw new Error('pricePerNight must be positive')
                if (input.devicePassword.length < 8) throw new Error('devicePassword must be at least 8 characters')
            },
            apply(ctx: ServiceCommandCtx<ApartmentsState>, input) {
                if (ctx.state.apartments[input.id]) throw new Error(`apartment ${input.id} already exists`)
                if (ctx.state.locks[input.lockId] || ctx.state.accounts[input.lockId]) throw new Error(`lock ${input.lockId} already exists`)
                ctx.state.apartments[input.id] = {id: input.id, title: input.title, host: ctx.account, pricePerNight: input.pricePerNight, lockId: input.lockId}
                ctx.state.locks[input.lockId] = {id: input.lockId, apartmentId: input.id, device: input.lockId, online: false, commands: {}, events: []}
                ctx.state.accounts[input.lockId] = {account: input.lockId, name: 'Lock ' + input.lockId, roles: ['device'], secret: hashSecret(input.devicePassword)}
                return {...ctx.state.apartments[input.id]}
            },
        }),
        /** Book: the dates are held at once; the payment is an INTENT the runner performs. */
        book: schemaCommand({apartmentId: 'string', from: 'date-string', to: 'date-string'}, {
            allow: ['guest'],
            validate(input) {
                if (input.from >= input.to) throw new Error('from must be strictly before to')
                if (nightsBetween(input.from, input.to) > 30) throw new Error('at most 30 nights')
            },
            apply(ctx: ServiceCommandCtx<ApartmentsState>, input) {
                const apartment = ctx.state.apartments[input.apartmentId]
                if (!apartment) throw new Error(`unknown apartment: ${input.apartmentId}`)
                for (const other of Object.values(ctx.state.bookings)) {
                    if (other.apartmentId == apartment.id && holdsDates(other) && overlaps(other, input)) {
                        throw new Error(`${apartment.id} is taken ${other.from}..${other.to}`)
                    }
                }
                const nights = nightsBetween(input.from, input.to)
                const request = opaqueRequestId(ctx)
                const id = 'bk-' + request
                const paymentId = 'pay-' + request
                if (Object.hasOwn(ctx.state.bookings, id) || Object.hasOwn(ctx.state.payments, paymentId)) {
                    throw new Error('booking request already used')
                }
                const booking: Booking = {
                    id, apartmentId: apartment.id, guest: ctx.account, from: input.from, to: input.to,
                    nights, total: nights * apartment.pricePerNight, state: 'pending', paymentId, codeArmed: false, ts: Date.now(),
                }
                ctx.state.bookings[id] = booking
                ctx.state.payments[paymentId] = {id: paymentId, bookingId: id, amount: booking.total, currency: CURRENCY, state: 'pending', ts: Date.now()}
                return {...booking}
            },
        }),
        /** Only while the payment has not left the building: once charged, the settlement decides. */
        cancelBooking: schemaCommand({bookingId: 'string'}, {
            allow: ['guest'],
            apply(ctx: ServiceCommandCtx<ApartmentsState>, input) {
                const booking = requireBooking(ctx.state, input.bookingId)
                if (booking.guest != ctx.account) throw new Error('only the guest who booked may cancel')
                if (booking.state != 'pending') throw new Error(`booking is ${booking.state}`)
                const payment = requirePayment(ctx.state, booking.paymentId)
                if (payment.state != 'pending') throw new Error('the payment is already in progress; wait for the settlement')
                booking.state = 'cancelled'
                payment.state = 'failed'
                payment.error = 'cancelled by the guest'
                return {id: booking.id, state: booking.state}
            },
        }),
        /** Effect outcome: the runner charged the provider (idempotent by the payment id). */
        paymentSubmitted: schemaCommand({paymentId: 'string', ref: 'string'}, {
            allow: ['system'],
            apply(ctx: ServiceCommandCtx<ApartmentsState>, input) {
                const payment = requirePayment(ctx.state, input.paymentId)
                if (payment.state == 'pending') { payment.state = 'submitted'; payment.ref = input.ref }
                return {id: payment.id, state: payment.state}
            },
        }),
        /** The provider's settlement (webhook, or the runner giving up): paid → a code and a lock intent; failed → declined.
         *  Every verified event is LEDGERED under its id (the requestId) whether or not it changed the payment. */
        paymentSettled: schemaCommand({paymentId: 'string', status: {enum: ['confirmed', 'failed']}, ref: 'string?', error: 'string?'}, {
            allow: ['system'],
            apply(ctx: ServiceCommandCtx<ApartmentsState>, input) {
                const payment = requirePayment(ctx.state, input.paymentId)
                const booking = requireBooking(ctx.state, payment.bookingId)
                // the same event twice (a redelivery past the receipt window) is the same fact
                const seen = ctx.state.events[ctx.requestId]
                if (seen) return {id: payment.id, state: payment.state, booking: booking.state, event: seen.id}
                const final = payment.state == 'confirmed' || payment.state == 'failed'
                ctx.state.events[ctx.requestId] = {
                    id: ctx.requestId, ts: Date.now(), paymentId: payment.id, status: input.status, applied: !final,
                    ...(input.ref ? {ref: input.ref} : {}), ...(input.error ? {error: input.error} : {}),
                }
                // a settlement is final: a later one is tracked, not applied
                if (final) return {id: payment.id, state: payment.state, booking: booking.state, event: ctx.requestId}
                if (input.ref) payment.ref = input.ref
                if (input.status == 'failed') {
                    payment.state = 'failed'
                    payment.error = input.error ?? 'declined'
                    if (booking.state == 'pending') booking.state = 'declined'
                    return {id: payment.id, state: payment.state, booking: booking.state}
                }
                payment.state = 'confirmed'
                if (booking.state == 'pending') {
                    booking.state = 'paid'
                    booking.code = String(randomInt(100000, 999999))
                    const lock = ctx.state.locks[ctx.state.apartments[booking.apartmentId]?.lockId ?? '']
                    if (lock) enqueueLockCommand(lock, 'set-' + booking.id, {kind: 'setCode', code: booking.code, bookingId: booking.id, requestedBy: 'system', expiresAt: Date.parse(booking.to)})
                }
                return {id: payment.id, state: payment.state, booking: booking.state}
            },
        }),
        /** The guest opens the door from the app: an intent for the lock, only during a paid stay. */
        unlock: schemaCommand({bookingId: 'string'}, {
            allow: ['guest'],
            apply(ctx: ServiceCommandCtx<ApartmentsState>, input) {
                const booking = requireBooking(ctx.state, input.bookingId)
                if (booking.guest != ctx.account) throw new Error('not your booking')
                if (booking.state != 'paid') throw new Error(`booking is ${booking.state}`)
                const day = today()
                if (day < booking.from || day >= booking.to) throw new Error('the stay is not today')
                const lock = ctx.state.locks[ctx.state.apartments[booking.apartmentId].lockId]
                const commandId = 'unlock-' + opaqueRequestId(ctx)
                if (Object.hasOwn(lock.commands, commandId)) throw new Error('unlock request already used')
                const command = enqueueLockCommand(lock, commandId, {kind: 'unlock', bookingId: booking.id, requestedBy: ctx.account,
                    expiresAt: Math.min(Date.now() + LOCK_UNLOCK_TTL_MS, Date.parse(booking.to))})
                return {commandId: command.id, state: command.state}
            },
        }),
        /** The device reports an executed command; a setCode done arms the guest's code. */
        lockReport: schemaCommand({commandId: 'string', ok: 'boolean', detail: 'string?'}, {
            allow: ['device'],
            apply(ctx: ServiceCommandCtx<ApartmentsState>, input) {
                const lock = lockOfDevice(ctx.state, ctx.account)
                const command = lock.commands[input.commandId]
                if (!command) throw new Error(`unknown command ${input.commandId} for ${lock.id}`)
                if (command.state != 'pending') return {id: command.id, state: command.state}
                command.state = input.ok ? 'done' : 'failed'
                if (input.detail) command.detail = input.detail
                pushEvent(lock, command.kind + (input.ok ? ' done' : ' failed'), input.detail)
                if (input.ok && command.kind == 'setCode' && command.bookingId) {
                    const booking = ctx.state.bookings[command.bookingId]
                    if (booking) booking.codeArmed = true
                }
                return {id: command.id, state: command.state}
            },
        }),
        lockHeartbeat: schemaCommand({battery: 'number'}, {
            allow: ['device'],
            apply(ctx: ServiceCommandCtx<ApartmentsState>, input) {
                const lock = lockOfDevice(ctx.state, ctx.account)
                lock.online = true
                lock.battery = input.battery
                lock.seenAt = Date.now()
                return {id: lock.id, online: true}
            },
        }),
        /** What happened at the door (the device validates codes locally against its view line). */
        lockEvent: schemaCommand({kind: {enum: ['code-entered', 'code-rejected', 'door-opened', 'tamper']}, detail: 'string?'}, {
            allow: ['device'],
            apply(ctx: ServiceCommandCtx<ApartmentsState>, input) {
                const lock = lockOfDevice(ctx.state, ctx.account)
                pushEvent(lock, input.kind, input.detail)
                return {id: lock.id, events: lock.events.length}
            },
        }),
    },

    // ============== views: one line per audience ==============
    views: {
        /** Anyone: apartments and their taken spans (no guest, no price paid). */
        apartments: {
            allow: 'public', keys: ['apartments', 'bookings', 'accounts'],
            project(state: ApartmentsState) {
                const list = Object.values(state.apartments).map(apartment => ({
                    id: apartment.id, title: apartment.title, pricePerNight: apartment.pricePerNight,
                    host: state.accounts[apartment.host]?.name ?? apartment.host,
                    taken: Object.values(state.bookings)
                        .filter(booking => booking.apartmentId == apartment.id && holdsDates(booking))
                        .map(booking => ({from: booking.from, to: booking.to})),
                }))
                return {apartments: list}
            },
        },
        /** A guest: my bookings with the payment state; the code only once the lock armed it. */
        myBookings: {
            allow: ['guest'], keys: ['bookings', 'payments'],
            project(state: ApartmentsState, principal: tServicePrincipal | null) {
                const bookings: Record<string, object> = {}
                for (const booking of Object.values(state.bookings)) {
                    if (booking.guest != principal?.account) continue
                    const payment = state.payments[booking.paymentId]
                    bookings[booking.id] = {
                        id: booking.id, apartmentId: booking.apartmentId, from: booking.from, to: booking.to, nights: booking.nights,
                        total: booking.total, state: booking.state, payment: payment?.state ?? 'pending',
                        ...(payment?.error ? {paymentError: payment.error} : {}),
                        ...(booking.codeArmed && booking.code ? {code: booking.code} : {}),
                    }
                }
                return {bookings}
            },
        },
        /** A host: the money — every payment of my apartments with the provider's events (the tracking view). */
        ledger: {
            allow: ['host'], keys: ['apartments', 'bookings', 'payments', 'events', 'accounts'],
            project(state: ApartmentsState, principal: tServicePrincipal | null) {
                const mine = new Set(Object.values(state.apartments).filter(apartment => apartment.host == principal?.account).map(apartment => apartment.id))
                const payments: Record<string, object> = {}
                for (const payment of Object.values(state.payments)) {
                    const booking = state.bookings[payment.bookingId]
                    if (!booking || !mine.has(booking.apartmentId)) continue
                    payments[payment.id] = {
                        id: payment.id, bookingId: booking.id, guest: state.accounts[booking.guest]?.name ?? booking.guest,
                        amount: payment.amount, currency: payment.currency, state: payment.state,
                        ...(payment.ref ? {ref: payment.ref} : {}), ...(payment.error ? {error: payment.error} : {}),
                        events: Object.values(state.events).filter(event => event.paymentId == payment.id)
                            .sort((a, b) => a.ts - b.ts).map(event => ({id: event.id, ts: event.ts, status: event.status, applied: event.applied, ...(event.error ? {error: event.error} : {})})),
                    }
                }
                return {payments}
            },
        },
        /** A host: my apartments, their bookings with guests, payments, lock health — one line per session. */
        hostBoard: {
            allow: ['host'], keys: ['apartments', 'bookings', 'payments', 'locks', 'accounts'],
            project(state: ApartmentsState, principal: tServicePrincipal | null) {
                const mine = Object.values(state.apartments).filter(apartment => apartment.host == principal?.account)
                const apartments: Record<string, object> = {}
                const now = Date.now()
                for (const apartment of mine) {
                    const lock = state.locks[apartment.lockId]
                    const pending = lock ? Object.values(lock.commands).filter(command => command.state == 'pending') : []
                    apartments[apartment.id] = {
                        id: apartment.id, title: apartment.title, pricePerNight: apartment.pricePerNight,
                        lock: lock ? {
                            id: lock.id, online: lock.online, battery: lock.battery ?? null,
                            pending: pending.length,
                            unavailable: pending.filter(command => !currentLockCommand(state, lock, command, now)).length,
                            events: lock.events.slice(-5),
                        } : null,
                    }
                }
                const bookings: Record<string, object> = {}
                for (const booking of Object.values(state.bookings)) {
                    if (!mine.some(apartment => apartment.id == booking.apartmentId)) continue
                    const payment = state.payments[booking.paymentId]
                    bookings[booking.id] = {
                        id: booking.id, apartmentId: booking.apartmentId, guest: state.accounts[booking.guest]?.name ?? booking.guest,
                        from: booking.from, to: booking.to, total: booking.total, state: booking.state,
                        payment: payment?.state ?? 'pending', ...(payment?.ref ? {ref: payment.ref} : {}), codeArmed: booking.codeArmed,
                    }
                }
                return {apartments, bookings}
            },
        },
        /** The device: ITS lock only — pending commands to execute, and the codes valid today. */
        myLock: {
            allow: ['device'], keys: ['locks', 'bookings', 'apartments'],
            project(state: ApartmentsState, principal: tServicePrincipal | null) {
                const lock = Object.values(state.locks).find(candidate => candidate.device == principal?.account)
                const commands: Record<string, LockCommand> = {}
                const codes: Record<string, {bookingId: string, from: string, to: string}> = {}
                if (!lock) return {lock: null, commands, codes}
                const now = Date.now()
                for (const command of Object.values(lock.commands)) {
                    const current = currentLockCommand(state, lock, command, now)
                    if (current) commands[current.id] = current
                }
                const day = today()
                for (const booking of Object.values(state.bookings)) {
                    if (booking.apartmentId != lock.apartmentId || booking.state != 'paid' || !booking.code) continue
                    if (day < booking.from || day >= booking.to) continue
                    codes[booking.code] = {bookingId: booking.id, from: booking.from, to: booking.to}
                }
                return {lock: {id: lock.id, apartmentId: lock.apartmentId}, commands, codes}
            },
        },
    },
} satisfies tServiceDefinition<ApartmentsState>

export type ApartmentsDefinition = typeof serviceDefinition





