// Generated by scripts/generate-examples.mjs; edit the source in the repository.
import assert from 'node:assert/strict'
import {createHook} from 'node:async_hooks'
import {setImmediate as nextTurn} from 'node:timers/promises'
import {createMemoryReplayStorage} from 'wenay-common2/replay'
import type {StorePatch} from 'wenay-common2/observe'
import {createServiceLeader, type tServiceDefinition} from './leader'

type State = {record: {value: number}}
const definition = {
    name: 'migration-check', storeId: 'migration-store', originId: 'migration-origin',
    initial: {record: {value: 7}}, commands: {}, version: 1,
} satisfies tServiceDefinition<State>

async function scenario(kind: 'missing' | 'throwing' | 'result') {
    const storage = createMemoryReplayStorage<[readonly StorePatch[]]>()
    const deps = {selfUrl: () => 'mem://migration-check', durable: {storage, everyEvents: 1}, log() {}}
    const original = createServiceLeader({...deps, definition})
    original.control.start()
    original.control.close()
    await nextTurn()

    // Observe resource lifetimes without reaching into the authority or its timer implementation.
    const timers = new Set<number>()
    let createdTimers = 0
    let constructing = false
    const hook = createHook({
        init(id, type) {
            if (constructing && type == 'Timeout') { timers.add(id); createdTimers++ }
        },
        destroy(id) { timers.delete(id) },
    })
    const failure = new Error('migration refused')
    let successfulMigrations = 0
    hook.enable()
    try {
        constructing = true
        try {
            assert.throws(function failedStartup() {
                createServiceLeader({...deps, definition: {
                    ...definition, version: 2,
                    ...(kind != 'missing' ? {migrate(state: State) {
                        if (kind == 'result') {
                            // An unreadable replacement must not delete the previous record first.
                            return {get replacement() { throw failure }} as unknown as State
                        }
                        state.record.value = 999
                        throw failure
                    }} : {}),
                }})
            }, kind != 'missing' ? function originalError(error) { return error == failure } : /no migrate\(\) is declared/)
        } finally { constructing = false }
        await nextTurn()
        await nextTurn()
        assert(createdTimers > 0, 'fixture must observe allocated timer resources')
        assert.equal(timers.size, 0, kind + ' migration startup retained timer resources')

        const produced = {record: {value: 0}}
        const migratedDefinition = {...definition, version: 2, migrate(state: State, from: number) {
            assert.equal(from, 1)
            assert.deepEqual(state.record, {value: 7}, 'failed migration preparation must not mutate restored state')
            successfulMigrations++
            produced.record.value = state.record.value * 10
            return produced
        }}
        const retried = createServiceLeader({...deps, definition: migratedDefinition})
        try {
            retried.control.start()
            assert.equal(retried.view.state().record.value, 70)
            produced.record.value = 999
            assert.equal(retried.view.state().record.value, 70, 'migration result must be detached from callback ownership')
        } finally { retried.control.close() }
        const restored = createServiceLeader({...deps, definition: migratedDefinition})
        try {
            assert.equal(restored.view.state().record.value, 70)
            assert.equal(successfulMigrations, 1)
        } finally { restored.control.close() }
    } finally { hook.disable() }
}

async function main() {
    await scenario('missing')
    await scenario('throwing')
    await scenario('result')
    console.log('PASS migration: failed callback/result preserves archive and releases timers; detached retry migrates once')
}

main().catch(function failed(error) { console.error(error); process.exitCode = 1 })
