// Generated by scripts/generate-examples.mjs; edit the source in the repository.
import {io} from 'socket.io-client'
import {createStore} from 'wenay-common2/observe'
import {syncStoreReplay, type StoreReplayState} from 'wenay-common2/observe'
import {createRpcClientHub, type RpcTokenProvider} from 'wenay-common2/rpc'
import type {ReaderFacade, DeviceFacade} from './host'

export type HomeEndpoint = {url: string, token: RpcTokenProvider}
type tReaderState = 'connecting' | 'live' | 'offline' | 'failed' | 'closed'
type HomeView = ReaderFacade['source'] extends StoreReplayState<infer S> ? S : never

// === A stable local Store over a replaceable process lifetime ===
export function createHomeReader(deps: HomeEndpoint) {
    const store = createStore<HomeView>({devices: {}})
    const health = createStore<{state: tReaderState, error: string | null}>({state: 'connecting', error: null})
    const hub = createRpcClientHub(
        function socket() { return io(deps.url, {transports: ['websocket'], forceNew: true, reconnectionDelay: 100, reconnectionDelayMax: 300}) },
        r => ({home: r<ReaderFacade>('home')}),
        {token: deps.token},
    )
    let closed = false
    let sync: ReturnType<typeof syncStoreReplay<typeof store.state>> | undefined
    const offDisconnect = hub.disconnectListen(function disconnected() {
        if (!closed) health.state.state = 'offline'
    })
    const ready = (async function connect() {
        await hub.promise
        await hub.facade.home.readyStrict()
        if (closed) throw new Error('reader closed during connection')
        sync = syncStoreReplay(store, hub.facade.home.func.source, {
            // Projection seq is local to a process. Every reconnect installs a fresh snapshot.
            prepareCatchUp() {
                if (!closed) health.state.state = 'connecting'
                return {reset: true}
            },
            onLive() {
                if (!closed) { health.state.state = 'live'; health.state.error = null }
            },
            onError(error: unknown) {
                if (!closed) { health.state.state = 'failed'; health.state.error = String(error) }
            },
        })
        await sync.ready
        if (closed) throw new Error('reader closed during initial snapshot')
        if (health.state.state == 'failed') throw new Error(health.state.error ?? 'reader failed')
    })()
    ready.catch(function connectFailed(error) {
        if (!closed) { health.state.state = 'failed'; health.state.error = String(error) }
    })

    function close() {
        if (closed) return
        closed = true
        offDisconnect()
        sync?.()
        hub.close()
        health.state.state = 'closed'
    }
    return {store, health, ready, view: {seq: () => sync?.seq() ?? -1, connections: hub.connectCount}, close}
}
export type HomeReader = ReturnType<typeof createHomeReader>

// === Device commands use the same transport; the server binds the device identity ===
export function createHomeDevice(deps: HomeEndpoint) {
    const health = createStore<{state: tReaderState, error: string | null}>({state: 'connecting', error: null})
    const hub = createRpcClientHub(
        function socket() { return io(deps.url, {transports: ['websocket'], forceNew: true, reconnectionDelay: 100, reconnectionDelayMax: 300}) },
        r => ({home: r<DeviceFacade>('home')}),
        {token: deps.token},
    )
    let closed = false
    const offConnect = hub.connectListen(function connected() {
        if (!closed) { health.state.state = 'live'; health.state.error = null }
    })
    const offDisconnect = hub.disconnectListen(function disconnected() {
        if (!closed) health.state.state = 'offline'
    })
    const ready = hub.promise.then(async function connected() { await hub.facade.home.readyStrict() })
    ready.catch(function failedConnection(error) {
        if (!closed) { health.state.state = 'failed'; health.state.error = String(error) }
    })
    function close() {
        if (closed) return
        closed = true
        offConnect(); offDisconnect()
        hub.close()
        health.state.state = 'closed'
    }
    return {ready, health, control: hub.facade.home.func.control, close}
}
export type HomeDevice = ReturnType<typeof createHomeDevice>
